--FINDING TRANSIT BETWEEN AIRPORTS USING AIRPORT NAME

"SELECT P1, P2, P3, P4, P1_START, P1_END, P2_END, P3_END, P4_END, P5_END
FROM
(
	SELECT R1.ID AS P1, R1.START_AIRPORT_ID AS P1_START, R1.END_AIRPORT_ID AS P1_END, R2.ID AS P2, R2.END_AIRPORT_ID AS P2_END,
	R3.ID AS P3, R3.END_AIRPORT_ID AS P3_END, R4.ID AS P4, R4.END_AIRPORT_ID AS P4_END,
	R5.ID AS P5, R5.END_AIRPORT_ID AS P5_END
	
	FROM ROUTE R1
	LEFT OUTER JOIN ROUTE R2
	ON 
	(
		R1.START_AIRPORT_ID=
		(
			SELECT ID FROM AIRPORT
			WHERE LOWER(NAME) = LOWER('B')
		)
		AND
		R1.END_AIRPORT_ID=R2.START_AIRPORT_ID
		AND
		R2.DEPARTURE_TIME > R1.ARRIVAL_TIME
	)
	LEFT OUTER JOIN ROUTE R3
	ON
	(
		R2.END_AIRPORT_ID=R3.START_AIRPORT_ID
		AND
		R3.DEPARTURE_TIME > R2.ARRIVAL_TIME
	)
	LEFT OUTER JOIN ROUTE R4
	ON
	(
		R3.END_AIRPORT_ID=R4.START_AIRPORT_ID
		AND
		R4.DEPARTURE_TIME > R3.ARRIVAL_TIME
	)
	LEFT OUTER JOIN ROUTE R5
	ON
	(
		R4.END_AIRPORT_ID=R5.START_AIRPORT_ID
		AND
		R5.DEPARTURE_TIME > R4.ARRIVAL_TIME
	)
)
WHERE
	(
		(
		(P1_END) = (SELECT ID FROM AIRPORT WHERE LOWER(NAME) = LOWER('Regional Airport C'))
		OR
		(P2_END) = (SELECT ID FROM AIRPORT WHERE LOWER(NAME) = LOWER('Regional Airport C'))
		OR
		(P3_END) = (SELECT ID FROM AIRPORT WHERE LOWER(NAME) = LOWER('Regional Airport C'))
		OR
		(P4_END) = (SELECT ID FROM AIRPORT WHERE LOWER(NAME) = LOWER('Regional Airport C'))
		OR
		(P5_END) = (SELECT ID FROM AIRPORT WHERE LOWER(NAME) = LOWER('Regional Airport C'))
		)
	);"